# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: CmdLine@2
  inputs:
    script: |
      python --version
      python3 --version

- task: FortifyScanCentralSAST@7
  inputs:
    scanCentralCtrlUrl: 'https://scsastctrl.uat.fortifyhosted.net/scancentral-ctrl'
    scanCentralClientToken: '$(ScanCentral.ClientToken)'
    sscUrl: 'https://ssc.uat.fortifyhosted.net/'
    sscCiToken: '$(ScanCentral.SscCiToken)'
    uploadToSSC: true
    applicationIdentifierType: 'byId'
    applicationVersionId: '10076'
    buildTool: 'none'
    pythonVersion: '3'